name:                partage-compiler
version:             0.1.0.0
github:              "kawu/partage-compiler"
license:             BSD3
author:              "Jakub Waszczuk"
maintainer:          "waszczuk.kuba@gmail.com"
copyright:           "2020 Jakub Waszczuk"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Natural Language Processing

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kawu/partage-compiler#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6 && < 0.7
- text >= 1.2 && < 1.3

library:
  source-dirs: src

# executables:
#   partage-compiler-exe:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - partage-compiler

# tests:
#   partage-compiler-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - partage-compiler
